services:
  vaultwarden:
    restart: always
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - vaultwarden:/data/
    ports:
      - 8062:80
    environment:
      - DATABASE_URL=${PG_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${FROM}
      - SMTP_FROM_NAME=VaultWarden
      - SMTP_SECURITY=starttls
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_KEY}
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM="Plain"
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=${DOMAIN_NAME}
      - INVITATION_ORG_NAME=HomeVault
      - INVITATIONS_ALLOWED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_DOMAINS_WHITELIST=${ALLOWED_DOMAINS}
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - TZ=Europe/Berlin
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
volumes:
  vaultwarden:
